// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwsoQ0ztsyiZkVZOWrqjSNSFBOoxfYS-Q',
    appId: '1:265938548349:web:0fab7e996b64c833c4a314',
    messagingSenderId: '265938548349',
    projectId: 'vivero-ceci-app',
    authDomain: 'vivero-ceci-app.firebaseapp.com',
    storageBucket: 'vivero-ceci-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrvV4yarOKT_08aX5ojV6ddQuuDDMbvCc',
    appId: '1:265938548349:android:3051b09b2f03aed0c4a314',
    messagingSenderId: '265938548349',
    projectId: 'vivero-ceci-app',
    storageBucket: 'vivero-ceci-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Gb5VfSEpH0CJhTY5PU5-WPWpv1ykNdM',
    appId: '1:265938548349:ios:ce9a5d07ff7a92aec4a314',
    messagingSenderId: '265938548349',
    projectId: 'vivero-ceci-app',
    storageBucket: 'vivero-ceci-app.firebasestorage.app',
    iosBundleId: 'com.example.viveroCeciApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Gb5VfSEpH0CJhTY5PU5-WPWpv1ykNdM',
    appId: '1:265938548349:ios:ce9a5d07ff7a92aec4a314',
    messagingSenderId: '265938548349',
    projectId: 'vivero-ceci-app',
    storageBucket: 'vivero-ceci-app.firebasestorage.app',
    iosBundleId: 'com.example.viveroCeciApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwsoQ0ztsyiZkVZOWrqjSNSFBOoxfYS-Q',
    appId: '1:265938548349:web:b8324694c23ca309c4a314',
    messagingSenderId: '265938548349',
    projectId: 'vivero-ceci-app',
    authDomain: 'vivero-ceci-app.firebaseapp.com',
    storageBucket: 'vivero-ceci-app.firebasestorage.app',
  );
}
